[agents]
192.168.0.20 ansible_user=vagrant 
192.168.0.21 ansible_user=vagrant
192.168.0.22 ansible_user=vagrant

#[dbservers]
#192.168.0.20 ansible_user=vagrant 
#192.168.0.21 ansible_user=vagrant
#192.168.0.22 ansible_user=vagrant

#[coordinators]
#192.168.0.20 ansible_user=vagrant 
#192.168.0.21 ansible_user=vagrant
#192.168.0.22 ansible_user=vagrant
