---
- hosts: 127.0.0.1
  vars:
     arangodb_download_url: https://download.arangodb.com/9c169fe900ff79790395784287bfa82f0dc0059375a34a2881b9b745c8efd42e/arangodb38/Enterprise/Linux/arangodb3e-linux-3.8.1.tar.gz
     tls_key_params: --host 192.168.0.22 --host 192.168.0.21 --host 192.168.0.21
  connection: local
  roles:
    - ansible/roles/arangodb-credentials-setup

- hosts: all
  roles:   
    - ansible/roles/arangodb

- hosts: all
  tasks:
    - name: Start the agent server
      ansible.builtin.systemd:
        name: agent.service
        state: started
      become: true

- hosts: all
  tasks:
    - name: Start the dbserver
      ansible.builtin.systemd:
        name: dbserver.service
        state: started
      become: true

- hosts: all
  tasks:
    - name: Start the coordinator server
      ansible.builtin.systemd:
        name: coordinator.service
        state: started
      become: true
