---
# tasks file for arangodb download and install

- name: Create the arangodb Group
  group:
    name: arangodb
    state: present 
  become: true

- name: Add arangodb User
  user:
    name: arangodb 
    create_home: no
    groups: arangodb
  become: true

- name: Install packages
  ansible.builtin.package: 
    pkg: "{{ item.package }}"
    update_cache: yes
  become: true
  loop: 
    - { package: "gcc" }
    - { package: "curl" }
    - { package: "net-tools" }

- name: Download and Install ArangoDB
  ansible.builtin.unarchive: 
    src: "{{ arangodb_download_url }}"
    dest: /usr/local
    remote_src: yes
  become: true

- name: Create required folders for Arangodb 
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
    owner: arangodb
    group: arangodb
  loop:
    - { path: "/var/tmp/arangodb3" }
    - { path: "/var/run/arangodb3" }
    - { path: "/var/log/arangodb3" }
    - { path: "/var/lib/arangodb3" }
    - { path: "/var/lib/arangodb3-apps" }
    - { path: "/etc/arangodb3" }
  become: true

- name: Copy configuration files to the /etc/arangodb/config
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '644'
  loop:
    - { src: "templates/systemdunits/agent.service.j2", dest: "/etc/systemd/system/agent.service"}
    - { src: "templates/systemdunits/coordinator.service.j2", dest: "/etc/systemd/system/coordinator.service"}
    - { src: "templates/systemdunits/dbserver.service.j2", dest: "/etc/systemd/system/dbserver.service"}
  become: true
